remote_theme: victorvoid/space-jekyll-template

title: Como publicar codigo estatico en github

# Site settings
description: Probar Pages

# User settings
username: VictorCabello
user_description: DevOps Consultant
user_title: Victor Cabello
email: vmeca87@gmail.com
twitter_username: VictorCabello
github_username:  VictorCabello
gplus_username:  VictorCabello
disqus_username: VictorCabello
