# Site settings
title: Victor Cabello Blog
email: vmeca87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal site where I can store and share my knowledge about
  java, groovy, vim, ruby, chef and all the cool stuf that I like
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://victorcabello.github.io" # the base hostname & protocol for your site
github_username:  VictorCabello

# Build settings
markdown: kramdown
