remote_theme: victorvoid/space-jekyll-template

title: Como publicar codigo estatico en github

# Site settings
description: Probar Pages

# User settings
username: VictorCabello
user_description: DevOps Consultant
user_title: Victor Cabello
email: vmeca87@gmail.com
twitter_username: VictorCabello
github_username:  VictorCabello
disqus_username: victorcabello
gplus_username:  VictorCabello
profile_picture: http://victorcabello.github.io/img/mifoto.jpg


links:
  section_1: # you can use any name
    - title: home # show on menu
      url: / #link
      key_trigger: 1 # link shortcut and show on the left of the title
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
