title: Blog Victor Cabello

# Site settings
description: Un lugar para compartir ideas

# User settings
username: VictorCabello
user_description: DevOps Consultant
user_title: Victor Cabello
email: vmeca87@gmail.com
twitter_username: VictorCabello
github_username:  VictorCabello
disqus_username: victorcabello
gplus_username:  VictorCabello
profile_picture: http://victorcabello.github.io/img/mifoto.jpg

# Build settings
theme: minima

sass:
    sass_dir: _sass
